### ISSUE TITLE
Provide Unreal Engine plugin

### ISSUE THREAD

**Issue by hridpath** [XRTK/XRTK-Core#70]
Currently there is very minimal support for HoloLens and virtually no support for windows Mixed Reality Headsets in Unreal Engine. The MRTK and XRTK have been focusing onn support for Unity only. 

I would like to propose that an Unreal Plugin be developed that can be imported into the Unreal Engine, to extend the same functionality that is used by the XRTK for Unity. I am not sure if this would be a seperate project or an inclusion to the existing project. 

I don't know that this would be a C++ project and because some IDEs do not support multiple project langauges, a seperate project would make sense. 
Blueprint code can be used to create examples and tests.

I would like to open this for discussion if possible.

**Comment by StephenHodgson** [comment]
That's a very interesting idea!

Unreal definitely has it's own set of challenges and unique problems associated to the engine. I'm curious to know if there's anything in the current toolkits that can be applied to both.

The lower level stuff I think should really be handled by OpenXR or the Platform.

What are other people's thoughts on this?

**Comment by FejZa** [comment]
"Currently there is very minimal support for HoloLens and virtually no support for windows Mixed Reality Headsets in Unreal Engine." as far as I know It's quite the opposite. There is support for WMR Headsets in Unreal. It's been there for a while now. But there is minimal support for HoloLens and what's there, is Pretty much "Preview".

Personally I haven't touched Unreal since circa 2011 so I can't Judge but I guess having XRTK for Unreal bascially IS a separate Project since it requires a complete reimplementation using Unreal APIs and blueprints etc.

Now here on GitHub the XRTK is clearly focused on Unity so far I think adding Unreal Projects would require giving all the repos / modules some sort of "Unity" prefix or postfix and then adding Unreal modules and so on.

Also having XRTK for Unreal requires a lot of manpower I guess. I think this is more of a longterm goal to watch but personally I think XRTK should stick with Unity for now and focus on covering platforms on Unity.

Just my thoughts.

**Comment by hridpath** [comment]
Thank you @FejZa. I was making my statement about direct support without having to include the Steam bridge. 

I have been able to create sample app that used the Steam to provide the bridge to the WHMD. But what I am looking for is a more direct support without the bridge.

**Comment by StephenHodgson** [comment]
I'm going to close this as I believe it's outside the scope of the project. 

Although I am interested in an Unreal version of the toolkit, it'll likely come with it's own set of challenges and unique set of solutions.

Hopefully OpenXR will provide a better path there.
